name: Build FRCrobotCodeGen302

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      #- name: Restore NuGet packages
      #  run: dotnet restore codeGenerator/src/FRCrobotCodeGen302/FRCrobotCodeGen302.sln

      - name: Build ApplicationData
        run: dotnet build codeGenerator/src/robotConfiguration/ApplicationData.csproj --configuration Release

      - name: Build CodeBeautifier
        run: dotnet build codeGenerator/src/CodeBeautifier/CodeBeautifier.csproj --configuration Release

      - name: Build Configuration
        run: dotnet build codeGenerator/src/Configuration/Configuration.csproj --configuration Release

      - name: Build CoreCodeGenerator
        run: dotnet build codeGenerator/src/CoreCodeGenerator/CoreCodeGenerator.csproj --configuration Release
      
      - name: Build DataConfiguration
        run: dotnet build codeGenerator/src/DataConfiguration/DataConfiguration.csproj --configuration Release

      - name: Build FRCrobotCodeGen302
        run: dotnet build codeGenerator/src/FRCrobotCodeGen302/FRCrobotCodeGen302.csproj --configuration Release

      - name: Build NetworkTablesUtils
        run: dotnet build codeGenerator/src/NetworkTablesUtils/NetworkTablesUtils.csproj --configuration Release
